
[env]
TERM = "xterm-256color"

[window]
decorations = "none"
decorations_theme_variant = "None"
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"
title = "Alacritty"

[window.dimensions]
columns = 120
lines = 60

[window.padding]
x = 2
y = 4

[font]
normal = { family = "MesloLGS Nerd Font Mono", style = "Regular" }
size = 14

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"


[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = false

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 600
blink_timeout = 0
unfocused_hollow = true

[mouse]
hide_when_typing = true

[general]

live_config_reload = true
import = [
    "~/.config/alacritty/keybindings.toml",

    # themes
    #"~/.config/alacritty/catppuccin-mocha.toml",
    "~/.config/alacritty/tokyo-night.toml",
]
