# Theme 
import = ["~/.config/alacritty/catppuccin-mocha.toml",
          "~/.config/alacritty/keybindings.toml",
]

live_config_reload = false

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
opacity = 0.98
blur = true

[font]
normal = { family = "MesloLGSNerdFontMono", style = "Regular" }
size = 12

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = false

[cursor]
style = { shape = "Block", blinking = "Always"}
blink_interval = 600
blink_timeout = 0
unfocused_hollow = true

[mouse]
hide_when_typing = true
