[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 14
[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "+"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "_"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Quit"
key = "q"
mods = "Control"

[window]
decorations = "none"
decorations_theme_variant = "None"
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"
title = "Alacritty"

[window.dimensions]
columns = 120
lines = 60

[window.padding]
x = 2
y = 4

[general]

live_config_reload = true
import = [
    "~/.config/alacritty/keybindings.toml",

    # themes
    #"~/.config/alacritty/catppuccin-mocha.toml",
    "~/.config/alacritty/tokyo-night.toml",
]
