[font.normal]
family = "MesloLGS NF"

[env]
TERM = "xterm-256color"

import = "~/.config/alacritty/catppuccin-mocha.toml"
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
