
[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 100, lines = 53 }
position = { x = 0, y = 0 }
decorations = "None"
opacity = 0.98
blur = true

[font]
normal = { family = "MesloLGS Nerd Font Mono", style = "Regular" }
size = 14

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = false

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 600
blink_timeout = 0
unfocused_hollow = true

[mouse]
hide_when_typing = true

[general]

live_config_reload = false

# Theme 
import = [
    "~/.config/alacritty/catppuccin-mocha.toml",
    "~/.config/alacritty/keybindings.toml",
]
